### ISSUE TITLE
How to install.. ?? 

### ISSUE THREAD

**Issue by dagnall53** [BerndCirotzki/raymarine_autopilot_pi#13]
Bernd, 
Sorry if this sounds very stupid, but I am not an OPENCPN user and I need to find out how to install this to assist someone.
First, is this different from the AutoTrackRaymarine plugin that appears in the plugins?  ??
Second.. where is the .tar to allow me to load it into OpenCPN?

The reason I ask is that I work (unpaid) with Luis at VelaNaviga, who sells the very reasonably priced ;-) NMEA3WIFI as a hobby.

This multiplexer accepts $STALK commands and sends them as Seatalk. (I helped with that coding)  

I have been trying to help a French user, but it appears he also has (only?)  the AutoTrackRaymarine plugin, and this does not seem to offer the $STALK output .. - it just offers an option to talk to an com port for an NGT-1:  which is a NMEA2000 interface! 

Many thanks!!
Dagnall

https://www.vela-navega.com/index.php/nmea3wifi

**Comment by BerndCirotzki** [comment]
Hi Dagnall,

if you use Windows, you can use the insaller "raymarine_autopilot_pi-1.0.2.1-msvc-x86_64-O_5.6.x.exe" for OpenCPN up to 5.6.2 or you use "raymarine_autopilot_pi-1.0.2.1-msvc-x86_64-O_5.8.x.exe" for the coming up Version 5.8.x .

if you uses other systems, you must compile yourself. It is not insert to the OpenCPN install modus. It was too compilcated for me. And too much work for only a hobby. 

Bernd

**Comment by dagnall53** [comment]
Thanks!

**Comment by rgleason** [comment]
The plugin should be available through PIM now. @dagnall53  This is now outdated and should be closed by the original poster, that is You!  Thanks.  Please close it!

**Comment by dagnall53** [comment]
CLOSED OUTDATED…
