### ISSUE TITLE
Autopilot going in Standby on its own 

### ISSUE THREAD

**Issue by Netxxl** [BerndCirotzki/raymarine_autopilot_pi#15]
Hi Bernd,

I installed your Plugin on android and it seems to be working overall, except for the settings dialog which cannot be used because it's too big and cannot be scrolled to the bottom where the ok button is.
So, I adjusted the settings direct in the conf file.
The main window is also not really scaled right on Android but functional. I put in the maximum Skalefaktor of 21.
But what happens mostly is that the autopilot will go on standby about every 10 minutes or so. 
And that's exactly what I was trying to prevent with the Plugin. 
It seems that the autopilot is confused by the echoed back stalk sentences from OpenCPN and shuts off? 
How can you prevent it from echoing everything to the output without compiling your own version of OpenCPN? 

Grüsse, 
Hans

**Comment by BerndCirotzki** [comment]
> Hi Bernd,
> 
> I installed your Plugin on android and it seems to be working overall, except for the settings dialog which cannot be used because it's too big and cannot be scrolled to the bottom where the ok button is.

Sorry, I have never used Android. So I don't know how to change.


 >So, I adjusted the settings direct in the conf file.

Very Clever !!

> The main window is also not really scaled right on Android but functional. I put in the maximum Skalefaktor of 21. But what happens mostly is that the autopilot will go on standby about every 10 minutes or so. And that's exactly what I was trying to prevent with the Plugin.

I seems, that your Problem is somewhere else. Is the voltage OK on the smartpilot ??

> It seems that the autopilot is confused by the echoed back stalk sentences from OpenCPN and shuts off? How can you prevent it from echoing everything to the output without compiling your own version of OpenCPN?

I did this to change the receive Sentencename from "STALK" to "RTALK" (It must be able to change this in the Seatalk NMEA Translator ... I developed my own.) and then filter the Sentences in OPENCPN not to send out "RTALK".
I know it is casted around the problems, but the develpoers of OPENCPN are not willing to change this mirroring nonsens.
 
PS : German ? ... 

Viele Grüße

Bernd

**Comment by Netxxl** [comment]
Ok, danke dir Bernd!

Yes, German.
But I write in English, so everyone here can follow. 

Yes, voltage etc is ok. We are long term Cruisers and on long passages after maybe average every 36 hours the autopilot goes to standby, maybe because too much usage or so. I hear it's a common problem with the raymarine seatalk 1 ones. I'm using a S3G with st6000 head. 

So I found your feature to revert to auto and old course helpful if no standby button has been pushed. 

But somehow when I use the Plugin it happens quite more often, about once every 10 minutes and I think it's because of the echo of OpenCPN. 

Unfortunately I cannot change the Stalk prefix on my seatalk converter for only receiving (I'm using the Yacht Devices YDNR-02N). 

I have to play around with the filters some, maybe I can find a way to filter those double messages. 

Thanks for your quick reply anyways. 

Hans

**Comment by rgleason** [comment]
Hans is this still a problem?  If not, please explain what you did and close this Issue.  The original poster should close the issue (you).

**Comment by Netxxl** [comment]
It's still a problem, but I guess not one we can solve here, so I will close here.

**Comment by rgleason** [comment]
Well if it is still doing this it certainly is a problem. Please reopen and advise exactly which version you are using and provide any detail that you think is important. How things are connected. Your settings etc. Also please reopen this Issue. Thanks.

**Comment by Netxxl** [comment]
Hi Rick,
It's certainly a problem, but not one we can solve in this Plugin, I guess. 
It's more the echoing "feature" of OpenCPN that needs to be able to be switched off.

**Comment by rgleason** [comment]
Please see  https://github.com/OpenCPN/OpenCPN/issues/3516
