### ISSUE TITLE
Testing on Raymarine ST EVO

### ISSUE THREAD

**Issue by poetsmeniet** [BerndCirotzki/raymarine_autopilot_pi#2]
Hi Bernd,

I compiled and enabled your fantastic plugin. I don't get the autopilot status and also don't see any outgoing msgs generated by the plugin..

I connected the PC with an Actisense NGW-1. I get all data from the seatalk ng bus instruments and use them on Opencpn without issue.

Is plugin written exclusively for your hardware? (stng->nmea converter?)

**Comment by poetsmeniet** [comment]
Looking at your code I can see you defined:
      STALKSendName = "STALK";
      STALKReceiveName = "STALK";

Is this related to you nmea/tsng converter?

**Comment by poetsmeniet** [comment]
Never mind, I see you coded this for seatalk 1

**Comment by BerndCirotzki** [comment]
Hello poetsmeniet,
... Yes, it is written for the NMEA Converter from http://www.gadgetpool.de. (named Seatalk LINK.)
This Hardware translates from the 3wire Seatalk Bus to Serial connection (ComPort) to NMEA Data. The Sentencename is defined as "STALK" in this Hardware when you buy this part. But when the Plugin is installed, you must see $STALK .... Messages in the NMEA Debug window from OPENCPN, when for example, you push on "Standby". So I only have the ST60 Instruments, so I only can test with them. So I thing it is only Seatalk1. The sentencename .. you can change in the Plugin preferences. ... For a Status, you must see NMEA Sentences from the Seatalk in NMEA Debug window !

**Comment by rgleason** [comment]
@poetsmeniet  Can this be closed now? You are the original poster and are the one who should close it.

**Comment by poetsmeniet** [comment]
Sure, closing
