### ISSUE TITLE
Language files and Crowdin Process

### ISSUE THREAD

**Issue by rgleason** [BerndCirotzki/raymarine_autopilot_pi#27]
Dear Bernd,

I see your PR here to 

https://github.com/rgleason/raymarine_autopilot_pi/pulls 

and I just wonder if these changes are in the language crowdin files too?  The reason I ask is if they are not, then the next time someone like Hakan or Dave or someone else updates all the language translation files, those changes will not be there. 

I think you should review the process with @Hakansv   https://github.com/Hakansv as he is well versed in this process.  I cannot find the Development documents anymore, which cover Language so I cannot provide a link to that (This is a separate problem). 

Once we know that the crowdin files have these improvements, we can probably merge them.

Also, I think you should add more description to the readme explaining that the type of autopilot needs to be set in preferences and providing a connection settings examples for each of the autopilot types. 

These additions should also be made in the manual too. 
https://opencpn-manuals.github.io/main/autopilot-rm/0.1/index.html
 
Thanks. Rick

**Comment by rgleason** [comment]
I found the Developer Manual now. There are some misleading pages....
See this page

https://opencpn-manuals.github.io/main/ocpn-dev-manual/0.1/dm-i18n.html

**Comment by Hakansv** [comment]
> I just wonder if these changes are in the language crowdin files too?

Sorry I'm historical lost here. What changes?
What's done in Crowdin until approx one week ago is covered in my update to Rick's Github for next plugin release.

**Comment by rgleason** [comment]
Hakan, sorry meant raymarine-autopilot.
Yes you updated it. I added your report to tp issues here. You can see the language update for raymarine_autopilot  https://github.com/jongough/testplugin_pi/issues/363

Bernd, Please review the process diagram here https://opencpn-manuals.github.io/main/ocpn-dev-manual/0.1/dm-i18n.html
and advise. Thanks.

**Comment by rgleason** [comment]
@BerndCirotzki  
Hakan writes:

> What's done in Crowdin until approx one week ago is covered in my update to Rick's Github for next plugin release.

Have you added these changes to Crowdin? Otherwise we can't accept your PR.

**Comment by BerndCirotzki** [comment]
Ok now I had some time and I took a look at this :
https://opencpn-manuals.github.io/main/ocpn-dev-manual/0.1/dm-i18n.html

The pot file is up to date! .... and there is discribed, that the work will be done by the Maintainers! This is not me! So I would not make any changes to Crowdin.
But however ... because the the POT file is there, I understand, that the translation is done automatic. So no more has to be done and you can delete my PR.
Sorry but this "concept" is a little too complicates for "fun developers" like me and I do not have the time for that.
The problem with this "translation concept" is, that the translation will be done by a Maschine. And I think this is bad.
I would like to make the translation myself. ... de_de.po ! at least the "german". And I tryed to make some more also, as best I can.
(Now I undersatnd why there are some stupid translations in Opencpn.
Example englich word "port" ... too meaning in german "Backbord", when it a direction, or "Hafen" when it is a harbour.)

Bernd

**Comment by Hakansv** [comment]
Bernd..
For translations a plugin dev can do its own upload to Crowdin or ask me or Pavel for assistance. I did it last time on Rick's request.
The process goes like this:

1. Plugin developer mark strings for translation. (Please only translatable strings and not code-alike text that a translator may don't understand how to handle.)
2. The ./po/POTFILES.in is updated to list files containing strings for translation.
3. The e.g. autopilot_route_pi.pot is created. I use VS2022 for that.
4. The pot-file is loaded to Crowdin
5. We all await our bellowed translators to share there time and knowledge to translate there's language. Nothing automatically here! The translators are OpenCPN users voluntarily working on Crowdin.
6. When we consider translators are ready we let Crowdin produce the .po-files, download and PR these to corresponding plugin. (Well, in between I use to build it to check the if all .po files builds wo errors. Often missed "\n". (If possible exclude them form translations)

If requested I sometimes do 2 -6.

Stupid translations. Not really.
Your example is well know. The English "port" can be used for many English meanings so equally different when it comes to other languages. The rule here is to use harbor, data-port and port for port side. When OpenCPN sees a translation for "port" he can't know which translation to use if there are many. So each developer has to take care here.  

If it helped or confused I don't know. I made a try.

**Comment by rgleason** [comment]
Thanks Hakan and Bernd.  I will close Bernd's PR, now that we all understand. Bernd, if you would like to make a new PR with just the readme changes, that would be great. Hopefully the translators will catch those inconsistencies for "port" and they will be updated next time the language files are done.

**Comment by rgleason** [comment]
Added the Process to https://github.com/jongough/testplugin_pi/issues/363 at the top.

Hakan I use some of your comments to augment this.

**Comment by rgleason** [comment]
Hakan I finished the description https://github.com/jongough/testplugin_pi/issues/363

Is it OK?
