### ISSUE TITLE
Language Translation Process

### ISSUE THREAD

**Issue by rgleason** [BerndCirotzki/raymarine_autopilot_pi#29]
Bernd, here is some info about language translation
https://opencpn-manuals.github.io/main/ocpn-dev-manual/0.1/dm-i18n.html

1. See [how to identify strings to be translated](https://opencpn-manuals.github.io/main/ocpn-dev-manual/0.1/dm-i18n.html)  " _(some string)"
2. After you know that you will not be adding more new translation "strings", notify Hakan.
3. He will clone your repository, make a .pot file and upload it to [crowdin OpenCPN](https://crowdin.com/) to be translated by human translators (not machine).
4. In about 2-3 weeks he will make his repository=yours, add the newly translated .po files and then make a PR to your PI.
5. You should then accept and merge the PR and re-publish the plugin (or advise me).

Later: I am going to do what Hakan suggested to help fix the conflicts.

**Comment by BerndCirotzki** [comment]
notify Hakan ... I would do, if anyone tell me how ! everthing's ready.

**Comment by BerndCirotzki** [comment]
Ok, ready,
now it's time to notify Hakan,
to pot file in your Repro is newest. the po for german, french, dutch, spain do not work, but you wrote, the will be updated over crowdin.
It would be good, when at least the "german" po file would be taken from my Repro, and not be made new !! I think, this is what I will do best myself.

**Comment by rgleason** [comment]
@Hakansv  Bernd would like to notify you to please update the pot and po files, because the newest po for german, dutch and spanish do not work. 

Is it correct that the best way to enter these translations for german dutch and spanish is to register for crowdin account, and become a translator for OpenCPN and Plugins? Otherwise local changes will always be overwritten?

Hakan, I think you should clone bernd's account for raymarine_pypilot and push changes to his account. Thanks.

(I made a PR to Bernd and had to resolve conflicts because of his more recent changes to autopilot_pi.cpp and all the po files. When resolving those conflicts I accepted Bernd's po files but they do not work because I believe the pot file changed. Is that possible? I did not notice any conflict there.)

**Comment by Hakansv** [comment]
> @Hakansv Bernd would like to notify you to please update the pot and po files, because the newest po for german, dutch and spanish do not work.
> 
Not working?? In more details please. But see below..

> Is it correct that the best way to enter these translations for german dutch and spanish is to register for crowdin account, and become a translator for OpenCPN and Plugins? Otherwise local changes will always be overwritten?
> 
If Crowdin is used the translators enter there translations for each language. 
When PR po-files from Crowdin existing ones will be updated not overwritten. If possible. 

> Hakan, I think you should clone bernd's account for raymarine_pypilot and push changes to his account. Thanks.
> 
> (I made a PR to Bernd and had to resolve conflicts because of his more recent changes to autopilot_pi.cpp and all the po files. When resolving those conflicts I accepted Bernd's po files but they do not work because I believe the pot file changed. Is that possible? I did not notice any conflict there.)


If the strings to translate in the code are changed or new added, a new pot-file has to be created and loaded to Crowdin.
If the use of Crowdin is not desired the pot-file has to be used by e.g. peoedit and perform all translations there. That will create updated po-files to commit locally.
But..
If the code is changed and you want to load new strings to Crowdin I can of course serve that. 
(If a po-file created locally is more complete just save it somewhere else before merge of a PR and copy it back afterwords.)
Bernd, if you think Crowdin is of no help we can of course take this plugin out?

Many words but here's a suggestion:
Looking at what's yesterday in Crowdin the translator's haven't put much of interest in this plugin
es_ES.po is 100% translated.
fr_FR is 65% translated.
For the rest nothing is done. Could that be what you say "not working"?

So, You could use your own po-files and copy the two mentioned above to your own repo?
I have attached two files:

[po_files.zip](https://github.com/BerndCirotzki/raymarine_autopilot_pi/files/13794509/po_files.zip)

**Comment by BerndCirotzki** [comment]
???
Now I don't understand anything. Rick say ... must to crowdin , now you say must not, and will be updated and not overwritten .?!
For me it really does not matter. I have 4 correct translation in my Repo. "de, nl, fr, es" and they work. I Only wanted them to upload to Rick's Repo, but always when doing it, there are conficts or they are wrong updated or overwritten. ...or what ever?!?

The 4 po files in Ricks Repro do not work because ... C- Compiler errors. (wrong updated ?)
..... Output errors (example for de) Doubledefinition :
C:/Users/Home PC 64Bit/Downloads/raymarine_autopilot_pi-master/po/de_DE.po:175: Mehrfachdefinition der Meldung...
1>C:/Users/Home PC 64Bit/Downloads/raymarine_autopilot_pi-master/po/de_DE.po:79: ...dies ist die Stelle der ersten Definition
1>C:\Program Files (x86)\Poedit\GettextTools\bin\msgmerge.exe: es ist 1 fataler Fehler aufgetreten

the easiest way I think is now to make a PR to Rick, with the 4 working po files, and they will not be changed be crowdin.

**Comment by Hakansv** [comment]
The use of Crowdin is not mandatory for a plugin but can be a help for users from different countries. But we have to rely on efforts from human translators. And for this plugin there is so far not much interest.
If you have four good translation files do use them and forget the files from Crowdin so far.  I agree.

**Comment by BerndCirotzki** [comment]
> And for this plugin there is so far not much interest.
Yes I think so it's very special.

what should I do now ?

**Comment by rgleason** [comment]
Ok Bernd,   I cannot fathom why my resolution of conflicts  in favor of your language changes did not work flawlessly, and would like to understand why.

Ok, I will make a PR from your repos to mine and see if it works.

Perhaps you problem has more to do with opencpn-libs not being updated?
I noticed that the opencpn-libs submodule branch has not been updated on your repository.
Are you sure it has been updated? There were some changes to opencpn-libs that you should have. This requires you to execute some git [commands for updating the submodule.](https://github.com/OpenCPN/opencpn-libs)  Scroll to the bottom and try 
https://github.com/OpenCPN/opencpn-libs#updating-to-latest-status 

Very sorry about all the trouble.

**Comment by BerndCirotzki** [comment]
No my Repro works !! I have fix everthing !
Ricks dose not work, because he has the wrong po files. And he is the manager of plugins.

**Comment by BerndCirotzki** [comment]
... sorry misunderstood. Ok Rick do it.

**Comment by rgleason** [comment]
Ok from the github web user interface, I will select "Pull Request" and make a "Compare" and then merge, keeping a careful eye on the direction. I hope we won't have conflicts this time.

rgleason/raymarine_autopilot **<----** BerndCirotzki/raymarine_autopilot_pi

**Comment by BerndCirotzki** [comment]
OK
