### ISSUE TITLE
Setting in OpenCPN 5.0.0

### ISSUE THREAD

**Issue by Dosheimer** [BerndCirotzki/raymarine_autopilot_pi#3]
Hi Bernd,
I have a Seatalk1 to NMEA0183 multiplexer as recommended from you and I have your Plugin running on OpenCPN 5.0.0.

Next weekend I have in mind to test the autopilot features at my Raymarine S2G together with an ST6002 on my boat.

The multiplexer already seems to be ready as I was able to connect to it by receiveing a response from it by typing "$SWVERSION" in putty telnet. 

But now I have some doubts how to do the connection setting in open CPN: How do your plugin know from which COM ports it shall receive the Seatalk1 data and to which COM port it shall send?

The settings possible in the OpenCPN connections window seems to be very limited for that
![image](https://user-images.githubusercontent.com/18244944/102280613-c9674a80-3f2d-11eb-9547-1e1e9ada9a3d.png)

Thanks for your assistance!
Dirk

**Comment by BerndCirotzki** [comment]
Hello Dirk,
when you have the NMEA Converter from "Frank Wallenwein" it sends and receives "$STALK" NMEA Sentences when activated.
Config in the Plugin "STALK" to receive and send (that's default).
you can see it for example with HTerm. Set "ausgabe auf diesen Port" to true. that is all.

**Comment by rgleason** [comment]
@Dosheimer  Can this be closed now?  You are the original poster and should close it if it is done.

**Comment by rgleason** [comment]
Bernd, the OP is not responding. You close this.
