### ISSUE TITLE
signalK connection

### ISSUE THREAD

**Issue by zweistein22** [BerndCirotzki/raymarine_autopilot_pi#33]
In opencpn it is possible to connect to a signalK server.
If a signalK server is connected to a raymarine_gateway  (nmea to Seatalk convverter), how can I send the raymarine_autopilot_pi data to that  connection?  
Is this already possible or would one need to implement it?
Best regards
Andreas

**Comment by BerndCirotzki** [comment]
Hello Andreas,
why do you want to use Signalk? where is the advantage?
I don't know of any external devices from well-known manufacturers that use Signalk.
It is always translated to NMEA 0183 or NMEA 2000. Well then you can send NMEA straight away and save yourself the additional source of error “SignalK”, and you can connect the NMEA Seatalk translator direct to OpenCPN via a serial connection.
Basically there is no “translation” from NMEA to Seatalk, only the bytes in the NMEA string are sent and received on the Seatalk bus. 
That's that, what the NMEA Seatalk connector has to do. Multiple devices can do this. e.g. "SeaTalk NMEA Link" 
https://www.gadgetpool.eu/product_info.php?products_id=54&PHPSESSID=ntunhqcqgllsc0hsqjeoo2u43u
Other devices can do this too, I built my own.
Example: $STALK,86,21,01,FE*4E -> Data on Seatalk bus: 0x86 0x21 0x01 0xfe

**Comment by zweistein22** [comment]
Hallo Bernd,

Du bist doch Deutscher?
Ja klar, signalK ist eine weitere Komplikation.
Ich habe halt mein nmea2seatalk an einem Raspberry pi angeschlossen. auf
dem läuft auch SignalK-server
Opencpn läuft auf einem Android Tablet im Wlan mit  nmea out über tcp 10110.
Funktioniert das so mit deinem Autopilot?

Ciao und wünsche dir einen schönen Tag.

Andreas
P.S. Auf meinem Tablet gibt es Probleme mit dem Config Dialog des
Autopilot. Es fehlen die Buttons, das ist ein Dimensionierungsproblem.
Wenn ich Zeit finde kann ich versuchen mich da reinzudenken und evtl.
Codechanges vorschlagen, bin aber gerade auf dem Boot.

**Comment by BerndCirotzki** [comment]
Opencpn läuft auf einem Android Tablet im Wlan mit  nmea out über tcp 10110.
Funktioniert das so mit deinem Autopilot?
Es fehlen die Buttons, das ist ein Dimensionierungsproblem. ... 

... habe ich nie getested auf Android. aber mal versuchen in den Einstellungen die Plugingrösse zu veränderen.
und Protokoll von SignalK auf TCP änderen. Auf dem Raspberrey einen anderen WLAN Server installieren, der serielle NMEA Daten verarbeitet.
gesendet wird dann aber nur NMEA0183 ... $STALK... einfach zum WLAN Server senden, und 1:1 an den Übersetzter weitergeben.
Wenn der Übersetzer das in Seatalk umwandelt und die Autopilot-Statusmeldunden von Seatalk in $STALK,84,... und zum Tablet sendet, sollte es gehen. (Das Problem ist dabei nur das beschiebene Spiegeln der $STALK Nachrichten von OpenCPN)

Ich bin der Meinung OpenCPN empfängt auch nur SignalK und sendet es nicht. z.B. keine SignalK kompatiblen RMB, XTE,APB Messages bei aktiver Route, wobei das möglicherweise inzwischen geändert wurde.
Aber wie gesagt, für mich ist SignalK nur eine Spielwiese für gelangweilte Entwickler ohne einen wirklichen Mehrwert.
