### ISSUE TITLE
What should I do?

### ISSUE THREAD

**Issue by rgleason** [BerndCirotzki/raymarine_autopilot_pi#6]
Bernd,
I was just thinking of updating Autopilot-Plugin (RM) to Jon Goughs Frontend2 version 1.0.222  (which is for Opencpn 5.7.1 plugins - we will leave the 5.6.2 plugins available) and I notice you did some work yesterday and made some commits.
Should I make a PR to my repos and use that now to then do the FE2 1.0.222 update?
Will that fit with your workflow?

**Comment by BerndCirotzki** [comment]
Hello Rick,

I saw that you are developing a new OpenCPN, so I built a new version and tested it with OpenCPN 5.7.1 ... works.
I also tried to deal with the subject of Cloudsmith etc ... but unfortunately I didn't really make much progress.
English <-> German translation of your discreption, the "testpulgin_pi" discreption .. etc.

If you want to do a PR that would be great, I don't know exactly how that works.
Make the code to yours if you like. I think it would be great, when it's on cloudsmith.

Bernd

**Comment by rgleason** [comment]
Bernd,
I will try to update it for 5.7.1 to build for all the various OS using Jon Gough's most recent version 1.0.222  Testplugin_pi  files which we call Frontend2 or FE2 v1.0.222

1. I will then push it up to my fork of your repository where  githb, circleci and appveyor builders will create all the various versions using the "ci" scripts and FE2  and cmakelists.txt.  
2. These will then be pushed to the cloudsmith directory.   
3. Then I can make a pull request to  opencpn/plugins  for the Beta catalog where we can try out the plugin using PIM (plugin manager) inside OpenCPN. 
4. To enable use of the Beta Catalog you need to add a line in your opencpn.ini file.   under [plugins]    catalogexpert=1 
5.  Then I will make a PR back to your repository, so that you can then merge it into your repository.
6. You then are current.  Because you are not yet set up with the ci builders and cloudsmith, github may show some errors, but you will still be able to build it locally yourself.
7. The code is yours, I am just adding tools to distribute it to various OS.

**Comment by BerndCirotzki** [comment]
That's great !
thank you ... we will do so.

**Comment by rgleason** [comment]
Ok, it may take me a day or two to get to it. Thanks.

**Comment by rgleason** [comment]
Closing. We've accomplished this.
