### ISSUE TITLE
Tested-works - a few issues to fix. A question..

### ISSUE THREAD

**Issue by rgleason** [BerndCirotzki/raymarine_autopilot_pi#8]
Do you want the plugin to be named
"raymarine_autopilot_pi"
"autopilot_raymarine_pi"
"autopilotRM_pi"?
obviously your choice, but I need to know before I make the 3 cloudsmith repositories.  
https://cloudsmith.io/~opencpn/repos/?page=1

The name can be changed reasonably easily now, (I can show you how) but later when it gets into the PIM plugin manager catalog and setup with a workflow landing in cloudsmith it cannnot be changed as easily..
https://cloudsmith.io/~opencpn/repos/?page=1

Two main issues:
1. At the end of the route, the boat simply turns 180 degrees and heads off in that direction. I think it should continue on the same course, and there should probably be an optional alert or alarm or something (watchdog_pi)?   The alarm might be too much to do right now.
2. For my high res screen the control menu is very small is there some way to fix that (maybe some options for a larger menu?) perhaps a slider to adjust the size?
You can see this in the screenshot attached.
![AutopilotRM_pi](https://user-images.githubusercontent.com/2363959/212548761-d8ed688c-9530-4107-bf71-cdb803643d3a.png)

Tested it with Marco Bergman's ais_simulator
https://github.com/marcobergman/ais_simulation

Another small suggestion:
3. At some point it would be good to simplify the icon and make it more black and white.

**Comment by BerndCirotzki** [comment]
Hello Rick,

1. please name it "raymarine_autopilot_pi".

2. How could you test without Raymarine Autopilot Sentences ? Track is made by Autopilot himself by getting APB,XTE and RMB. The plugin works not like "autopliot_track_pi" !

3. In the ".fbp" File I habe forbidden to change the size. Ok, I see it would be needed for high res screen (I have never used).
    you meen ... set the size of the plugin via slider? Isn't it enough to allow chaning the size ?

**Comment by rgleason** [comment]
1. ok will add that as cloudsmith repos
2. I've been sending EC  apb using ais_simulator by marcobergman.  I am just assuming that the seatalk to nmea0183 translation works.  Is that ok?   Wouldn't this autopilot work as long as there are Nmea0183  with EC apb sentences?  Doesn't need to be translated to and from Seatalk?
3.  The graphics need to be scaled up somehow. I tried to adjust the fpb file and that effort failed and it would not compile. Any way that would scale the graphics and controling icons/buttons up so that it could be used would be good.

**Comment by BerndCirotzki** [comment]
I changed the plugin the be able to be resized. But 205 Size is important for making in smaler when you disable the Autopilot parameters in the preferences.

to point 2:  Yes ! thats the way. Opencpn send out APB and RMB when a route is aktiv to the NMEA <-> Seatalk Converter
                 When the Autopilot is aktiv and send date to the NMEA/Seatalk converter, the Autopilot data will be Converted to
                 NMEA Data send to Opencpn. Example : $STALK,84,26,A2,88,40,00,FE,02,06*15 (this is a Standby)
                 When pushing Buttons on the plugin Keystroke Sentence will be send out to NMEA. Try it and see on NMEA
                 Window.
to point 3 : Same problem. ... compiling fpb file copy 's everything to src ! .h file to include, that's all.

**Comment by BerndCirotzki** [comment]
I added a slider in in pref-dialog to change the plugin size.

**Comment by rgleason** [comment]
I am assuming this works now, and am closing it.
