### ISSUE TITLE
High Res Display,  Control Panel is Better - some adjustments needed

### ISSUE THREAD

**Issue by rgleason** [BerndCirotzki/raymarine_autopilot_pi#9]
Bernd, Thank you!  Pulled your changes to my repos, and built locally and tested.

The control panel is much better. There are some adjustments needed.
For reference, I have a display resolution of 3840 x 2400 and the Windows 11  "Display" "Scale" is set to the recommended 250% .
We need a little more ability to zoom the png bigger. Also the separate icons in the control panel  seem to be cut off and need more area. Don't know how that is fixed.... 
See screenshots please.
![Scale-adjust-small](https://user-images.githubusercontent.com/2363959/214079350-2b5d3078-b513-4d8c-bc58-1246216e6de8.png)
![Zoomed-to-10](https://user-images.githubusercontent.com/2363959/214079364-92876d5b-9a2c-41dd-be61-e94ad4485351.png)

I will try testing some more.

**Comment by BerndCirotzki** [comment]
added "FromDIP(wxSize(..., ...))" for high dpi. I found this feature in xwwidgets. It was new for me. I tested it with changing the scale Factor in Windows 10. I do not have such a high reolution on my PC.

**Comment by rgleason** [comment]
I should see if this is working better when I get back.

**Comment by rgleason** [comment]
This problem appears to be fixed with 2.0.2.0 !  It shows at the right size and all the buttons are there. Thank you Bernd!
